### ISSUE TITLE
A Small Doubt

### ISSUE THREAD

**Issue by ariv797** [thevickypedia/Jarvis#13]
What are you supposed to write for the offline_receive_user, offline_receive_pass and offline_sender functions in helper_fuctions.aws_clients. A name or a phone number?

Are you supposed to write a date(12.08.2020) or a word(12th August 2020) for the birthday function?

PS: Skip to 4:35 in this youtube video:-   https://www.youtube.com/watch?v=d_4YJQsaAZ8  J actually does have print() functions

PPS: I thought it is quite ironic that this Jarvis runs on AWS while Ironman uses Oracle for his Jarvis in Ironman 2

**Comment by ariv797** [comment]
Exactly where in the docs is the definition of converted.replace()?

**Comment by ariv797** [comment]
Can you also pls tell me why chatter_bot function not available for windows?

**Comment by thevickypedia** [comment]
> Exactly where in the docs is the definition of converted.replace()?

converted is a `str` so `.replace` should follow one another. Refer to the docs [here](https://docs.python.org/3/library/stdtypes.html#str.replace)

**Comment by thevickypedia** [comment]
@ariv797 There are some libraries for which dependencies fail to get installed in chatbot for windows. You can try to reproduce it trying chatbot as a separate project on a windows machine. They might have fixed the issue with the recent [commit](https://github.com/gunthercox/ChatterBot/commit/d911b4ac46e122308a759ea6ec67b666136e3026), I'd like to remove the entire chatbot feature from Jarvis as it provides very less to no value.
