### ISSUE TITLE
Personal Cloud Compatibility

### ISSUE THREAD

**Issue by ariv797** [thevickypedia/Jarvis#15]
The module 'appscript' is only for MacOS, is there a way to create the personal cloud feature for Windows?

**Comment by thevickypedia** [comment]
All it does is to open a terminal in the background and executes a said command. To answer your question, yes it can be done in Windows and I'm planning on integrating soon. Simply use `cmd /c` - executes a command and terminates the window or `cmd /k` - executes a command and retains the window.
```
import os
os.system('cmd /c "python3 server.py"')
```
> :warning: &nbsp; Note: Personal Cloud feature is still in its infancy. I'd not suggest relying on it as it lacks encryption. I will be working on fixing it real soon.
