### ISSUE TITLE
getting error while running jarvis.py

### ISSUE THREAD

**Issue by jsdpr15** [thevickypedia/Jarvis#22]
Sir,
i am get this error while Jarvis.py
" from resource import RUSAGE_SELF, getrusage
ModuleNotFoundError: No module named 'resource'"

Python Version : 3.10.3
Windows : 11 Pro

**Comment by thevickypedia** [comment]
Jarvis currently works only on MacOS
https://github.com/thevickypedia/Jarvis#readme#:~:text=Platform%20Supported

**Comment by thevickypedia** [comment]
Windows support is now back and tested working in a Win 10 machine. I'm not aware of any potential changes for Win 11. You can check and update me if something obvious needs fixing.

**Comment by thevickypedia** [comment]
`Speedtest` is an external module from [speedtest-cli](https://github.com/sivel/speedtest-cli)
Can you check if the module is installed with the right version.
https://github.com/thevickypedia/Jarvis/blob/master/lib/win_requirements.txt#L30 
I'd suggest running
`pip uninstall --no-cache-dir speedtest-cli`
and then run
`pip install --no-cache speedtest-cli==2.1.3`

**Comment by thevickypedia** [comment]
I'm closing this issue, please re-open or create a new issue if you still have issues starting up Jarvis
