### ISSUE TITLE
Feature request - Plugin system

### ISSUE THREAD

**Issue by Akul2010** [thevickypedia/Jarvis#31]
Hello, I just wanted to ask if you plan on making a plugin system + marketplace. It would make it much easier to develop new features without tampering with the core.

**Comment by thevickypedia** [comment]
Thanks for the suggestion. A similar approach was in my TODO list but not just a priority.
I thought of migrating Jarvis to a celery cluster and setup entrypoints which can pretty much accept any module as plug and play.
I will eventually get the code to such a state but it won't be any time soon.

**Comment by Akul2010** [comment]
Maybe take a look at my voice assistant code at https://github.com/Akul-AI. I made another issue asking if you would like to collaborate with me on this.

**Comment by Akul2010** [comment]
Hi, I made a new branch (see v2) that also supports JS plugins. It's also really easy to use.
