### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by Akul2010** [thevickypedia/Jarvis#32]
Hi, I am making an AI similar to this, would you like to contribute? Find code at https://github.com/Akul-AI

**Comment by thevickypedia** [comment]
I did take a look at your code and I'm pretty impressed with the plug-in part.
As you may have noticed, a lot of my stuff is related to home automation and making boring daily tasks exciting.
With that in mind, let me know where you'd like me help out. Let's go from there.
I'm closing this issue, you can reach out to me at https://vigneshrao.com/contact
