### ISSUE TITLE
Which smart bulbs can you connect to MagicHome app?

### ISSUE THREAD

**Issue by ariv797** [thevickypedia/Jarvis#7]
I was planning on buying a smart bulb for my room and wanted to connect it to Jarvis. But I don't know which brand or model of bulbs to buy which is compatible with the MagicHome app. Can you please help with some suggestions?

**Comment by thevickypedia** [comment]
I was looking for the same and found this on [amazon](https://www.amazon.com/dp/B08C7GY43L/)

**Comment by ariv797** [comment]
Is this available on amazon.in?
